[project]
name = "rosstat-flc"
version = "2.0.0b18"
description = "Tool for format-logistic control of reports sent to RosStat"
authors = [{ name = "Никита Рябинин", email = "ryabinin.ne@gmail.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
keywords = [
    "flc",
    "tool",
    "control",
    "processing",
    "report",
    "rosstat",
    "fsgs",
    "format",
    "format-logistic",
    "russian-specific",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
    "lxml==5.4.0",
    "numpy==2.2.6",
    "multidict==6.6.3",
    "lark[interegular]==1.2.2",
]

[project.urls]
Repository = "https://github.com/WoolenSweater/rosstat-flc"
Changelog = "https://github.com/WoolenSweater/rosstat-flc/blob/master/CHANGELOG.md"

[dependency-groups]
dev = [
    "black==24.10.0",
    "ruff==0.5.7",
]

[tool.hatch.build.targets.sdist]
include = ["rosstat"]

[tool.hatch.build.targets.wheel]
include = ["rosstat"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
